---
# Example playbook pulling in roles

- hosts: all
  become: yes
  roles:
    - common
    - azure_cli
  when: ansible_os_family == 'Debian'

##- hosts: tag_managed_by_ansible
##  become: yes
##  roles:
##    - pip
##    - docker
##  vars:
##    pip_install_packages:
##      - name: docker

...
